# Default values for ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: default
image:
  repository: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_retail-store-sample-app/ui
  tag: 353b6520d6d09e8683dc976c0a130ee83ccb3a8d
swan_ingress:
  swan_host: www.swanpyaetun.com
  swan_acm_certificate_arn: arn:aws:acm:ap-southeast-1:655355946217:certificate/fe3c2710-f428-4285-abf5-cdbac143ef92