---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: checkout-redis
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: checkout
      app.kubernetes.io/instance: checkout
      app.kubernetes.io/component: redis
      app.kubernetes.io/owner: retail-store-sample
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: app
      podSelector:
        matchLabels:
          app.kubernetes.io/name: checkout
          app.kubernetes.io/instance: checkout
          app.kubernetes.io/component: service
          app.kubernetes.io/owner: retail-store-sample
    ports:
    - protocol: TCP
      port: 6379