---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: catalog
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: catalog
      app.kubernetes.io/instance: catalog
      app.kubernetes.io/component: service
      app.kubernetes.io/owner: retail-store-sample
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: app
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ui
          app.kubernetes.io/instance: ui
          app.kubernetes.io/component: service
          app.kubernetes.io/owner: retail-store-sample
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: app
      podSelector:
        matchLabels:
          app.kubernetes.io/name: catalog
          app.kubernetes.io/instance: catalog
          app.kubernetes.io/component: mysql
          app.kubernetes.io/owner: retail-store-sample
    ports:
    - protocol: TCP
      port: 3306